### ISSUE TITLE
get_data_bc(collection = 'dem') error

### ISSUE THREAD

**Issue by hydropatch** [deankoch/rasterbc#1]
I was excited to find this package to be able to download dem tiles directly in r. Unfortunately, I get this error when I try to download tiles: 

URL 'https://g-624536.53220.5898.data.globus.org/1/published/publication_278/submitted_data/dem/blocks/dem_092H.tif': status was 'SSL peer certificate or SSH remote key was not OK'

Let me know if you can help with this.

Thanks

**Comment by deankoch** [comment]
Hi Pat, thanks for your interest and thanks for letting me know about this issue! I think I can help.

It looks like the Globus endpoint domain for my collection was recently changed. This broke the DEM file links that were hard-coded in the package. Fortunately, I see that [FRDR now hosts permanent links](https://www.frdr-dfdr.ca/docs/en/change_log/). These should automatically redirect to the current location on Globus.

I have updated the development version of the package to use the permanent links. If you reinstall using `devtools::install_github('deankoch/rasterbc')`, your `getdata_bc` call should now work. 

I'll get to work on a CRAN update ASAP.

**Comment by deankoch** [comment]
The package is now patched (v1.0.2) and on CRAN. Update using `install.packages('rasterbc)` and downloads should work again
